- name: apt update
  apt:
    update_cache: yes

- name: install tools
  apt:
    name: "{{ pkglist }}"
    state: present
  vars:
    pkglist:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add repo key
  apt_key:
    url: https://getenvoy.io/gpg
    state: present

- name: add envoy repo
  apt_repository:
    repo: deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb {{ ansible_distribution_release }} stable
    state: present
    filename: envoy

- name: apt update
  apt:
    update_cache: yes

- name: install envoy
  apt:
    name: "{{ pkglist }}"
    state: present
  vars:
    pkglist:
      - getenvoy-envoy

